import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Affiliation from "./Affiliation";
import LatestNews from "@/Components/LatestNews";
import Head from "next/head";
import Courses from "@/Components/Courses";
import WhyToChoose from "@/Components/WhyToChoose";
import Advantages from "@/Components/Advantages";
import TextSlider from "@/Components/TextSlider";
import Alumini from "@/Components/Alumini";
import FAQS from "@/Components/FAQS";
import Footer from "@/Components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-oFTde9eVe/1n7iZAA4PvsInRv8zt3UmJ/2QZ5enF32KJTFnMf3+Z61fg/PJrS9g0"
          crossOrigin="anonymous"
        />
      </Head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* bg-[size:6rem_4rem] */}
        
        <Navbar />
        <div className="flex flex-col">
          <TextSlider/>
          {children}
          <LatestNews />
          <Courses/>
          <WhyToChoose/>
          <Advantages/>
          <Alumini/>
          <Affiliation />
          <FAQS/>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
